[project]
name = "scipygui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nicegui>=2.23.3",
    "numpy>=2.3.2",
    "pydantic>=2.11.7",
    "scipy>=1.16.1",
]
